Repository DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE, pull requests merged in 2023-08, with the labels that each got.

#306 Feat/#300 추가 게임오버 화면에 띄울 코인보상 View
  MC3Team18/MC3Team18/Global/Components/Games/DailyQuestPrizeView.swift
  MC3Team18/MC3Team18/Global/Components/Games/GameCoinPrizeView.swift
  MC3Team18/MC3Team18/Global/Extension/ColorExtension.swift
  MC3Team18/MC3Team18/Global/Extension/ViewExtension.swift
  MC3Team18/MC3Team18/Global/Modifier/PostNoBillsJaffnaText.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/GamePrizeGradient1.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/GamePrizeGradient2.colorset/Contents.json
Labels: Feat

#310 UI/#308: 수정 일시정지 & 게임 오버 버튼 스타일 추가 & 적용
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Games/AccentButton.swift
  MC3Team18/MC3Team18/Global/Components/Games/AccentButtonLabel.swift
  MC3Team18/MC3Team18/Global/Components/Games/GameButtonLabel.swift
  MC3Team18/MC3Team18/Global/Components/Games/GameOverButtonLabel.swift
  MC3Team18/MC3Team18/Global/Components/Games/TouchedButton.swift
  MC3Team18/MC3Team18/Global/Components/Style/AccentButtonStyle.swift
  MC3Team18/MC3Team18/Global/Components/Style/GameOverButtonStyle.swift
  MC3Team18/MC3Team18/Global/Components/Style/PauseButtonStyle.swift
  MC3Team18/MC3Team18/Global/Extension/ColorExtension.swift
  MC3Team18/MC3Team18/Global/Extension/ViewExtension.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/AccentButtonText.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonAccentGameOver.imageset/ButtonAccent.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonAccentGameOver.imageset/ButtonAccent@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonAccentGameOver.imageset/ButtonAccent@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonAccentGameOver.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOver.imageset/GameOverBtn.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOver.imageset/GameOverBtn@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOver.imageset/GameOverBtn@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOverBorder.imageset/ButtonGameOverBorder.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOverBorder.imageset/ButtonGameOverBorder@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOverBorder.imageset/ButtonGameOverBorder@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPause.imageset/PauseBtn.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPause.imageset/PauseBtn@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPause.imageset/PauseBtn@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPauseAccent.imageset/ButtonPauseAccent.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPauseAccent.imageset/ButtonPauseAccent@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPauseAccent.imageset/ButtonPauseAccent@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPauseAccent.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonTouchedGameOver.imageset/ButtonTouched.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonTouchedGameOver.imageset/ButtonTouched@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonTouchedGameOver.imageset/ButtonTouched@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonTouchedGameOver.imageset/Contents.json
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameOverView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakPauseView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
Labels: UI

#315 UI/#307 구현 GameOverView PrizeView 연결
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Games/DailyQuestPrizeView.swift
  MC3Team18/MC3Team18/Global/Components/Games/GameCoinPrizeView.swift
  MC3Team18/MC3Team18/Global/Components/Home/TrophyView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameOverView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
Labels: UI

#317 UI/#316 수정 GameOverView Button 레이아웃
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameOverView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakPauseView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakTutorialView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameOverView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
Labels: UI

#318 Feat/#312: 구현 상점 구매 기능 추가 (일부 완성)
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Home/TrophyView.swift
  MC3Team18/MC3Team18/Global/Components/Shop/ShopAccessoriesScrollView.swift
  MC3Team18/MC3Team18/Global/Components/Shop/ShopHeaderView.swift
  MC3Team18/MC3Team18/Global/Enum/ShopItemData.swift
  MC3Team18/MC3Team18/Global/Extension/IntExtension.swift
  MC3Team18/MC3Team18/MC3Team18App.swift
  MC3Team18/MC3Team18/Resources/Item.json
  MC3Team18/MC3Team18/View/ShopView.swift
Labels: Feat

#320 Feat/#319: 수정 게임 도중 얼굴이 인식 안될 때 텍스트 변경
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: Feat

#322 Feat/#321 차곡차곡 1줄 클리어 시 추가시간 3초 -> 1초로 하향
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: Feat

#324 UI/#323 제거 반짝반짝, 차곡차곡 점수표시 쉼표
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: UI

#329 Feat/#327 추가 DailyMission 완료 시 보상 제공 기능
  MC3Team18/MC3Team18/Global/Components/Games/DailyQuestPrizeView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameOverView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: Feat

#332 UI/#328 수정 ShopView 디자인 변경에 따른 레이아웃 수정, 구현 구매 기능
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Shop/ShopAccessoriesScrollView.swift
  MC3Team18/MC3Team18/Global/Components/Shop/ShopHeaderView.swift
  MC3Team18/MC3Team18/Global/Enum/ItemCategory.swift
  MC3Team18/MC3Team18/Global/Enum/ShopItemData.swift
  MC3Team18/MC3Team18/Global/Extension/ColorExtension.swift
  MC3Team18/MC3Team18/Global/Extension/ImageExtension.swift
  MC3Team18/MC3Team18/Global/Extension/ViewExtension.swift
  MC3Team18/MC3Team18/Global/Modifier/PretendardText.swift
  MC3Team18/MC3Team18/MLModel/Trill_35_05_50.mlmodel
  MC3Team18/MC3Team18/MLModel/Voice_35_05_75.mlmodel
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/Gradient/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/Gradient/GradientRed1.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/Gradient/GradientRed2.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/Gradient/GradientYellow1.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/Gradient/GradientYellow2.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/Gradient/GradientYellowShadow.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/InUseButton/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/InUseButton/InUse.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/InUseButton/InUseFont.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/InUseButton/InUseShadow.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/itemBox.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/itemBox.imageset/itemBox.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/itemBox.imageset/itemBox@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/itemBox.imageset/itemBox@3x.png
  MC3Team18/MC3Team18/Resources/Item.json
  MC3Team18/MC3Team18/View/RecordView.swift
  MC3Team18/MC3Team18/View/ShopView.swift
Labels: Feat, UI

#336 Asset/#335 변경 Shop 아이템 이미지 파일이름 영어 > 한글
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/bubbleCow.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/bubbleCow.imageset/bubbleCow.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/bubblePurple.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/bubblePurple.imageset/bubblePurple.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/bubbleRainbow.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/bubbleRainbow.imageset/bubbleRainbow.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/bubbleSevenStar.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/bubbleSevenStar.imageset/bubbleSevenStar.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/cap.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/cap.imageset/cap.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/flower.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/flower.imageset/flower.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/mustache.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/mustache.imageset/mustache.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/starMint.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/starMint.imageset/starMint.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/starPink.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/starPink.imageset/starPink.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/starPurple.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/starPurple.imageset/starPurple.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/starRainbow.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/starRainbow.imageset/starRainbow.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/sunglasses.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/sunglasses.imageset/sunglasses.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/sunglassesGreen.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/sunglassesGreen.imageset/sunglassesGreen.pdf
  MC3Team18/MC3Team18/Resources/Item.json
Labels: Asset

#339 Asset/#338 수정 차곡차곡 캐릭터, 입모양 이미지, 컵 입모양 우 이미지
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterInActive.imageset/ChagokCharacterInActive.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterInActive.imageset/ChagokCharacterInActive@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterInActive.imageset/ChagokCharacterInActive@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouthCheekPuff.imageset/ChagokMouthCheekPuff.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouthCheekPuff.imageset/ChagokMouthCheekPuff@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouthCheekPuff.imageset/ChagokMouthCheekPuff@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouthCheekPuff.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouthU.imageset/ChagokMouthU.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouthU.imageset/ChagokMouthU@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouthU.imageset/ChagokMouthU@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouthU.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/YellowCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/YellowCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/YellowCup@3x.png
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Asset

#343 Feat/#341 구현 ShopView 구매 전 확인 팝업
  MC3Team18/MC3Team18/Global/Components/Shop/ShopAccessoriesScrollView.swift
  MC3Team18/MC3Team18/Global/Components/Shop/ShopHeaderView.swift
  MC3Team18/MC3Team18/Global/Components/Shop/ShopItemPurchaseView.swift
  MC3Team18/MC3Team18/Global/Enum/ShopItemData.swift
  MC3Team18/MC3Team18/Global/Extension/ColorExtension.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/NegativeRed.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/ShopButton/BuyGradient.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/xmarkIcon.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/xmarkIcon.imageset/xmarkIcon.pdf
  MC3Team18/MC3Team18/Resources/Item.json
  MC3Team18/MC3Team18/View/ShopView.swift
Labels: Feat

#345 UI/#342: 수정 Chagok 다시 보지 않기 버튼 레이아웃
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
Labels: UI

#346 Feat/#344 구현 HomeView에서 Item.json 파일 Fetch하도록 수정
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Shop/ShopItemBoxView.swift
  MC3Team18/MC3Team18/Global/Components/Shop/ShopItemScrollView.swift
  MC3Team18/MC3Team18/Global/Components/Shop/ShopPopupCharacterView.swift
  MC3Team18/MC3Team18/Global/Components/Shop/ShopPopupView.swift
  MC3Team18/MC3Team18/MC3Team18App.swift
  MC3Team18/MC3Team18/Model/ShopItemData.swift
  MC3Team18/MC3Team18/Model/ShopItemViewModel.swift
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/ShopView.swift
Labels: Feat

#348 Feat/#347 구현 버블버블게임 아이템 적용(풍선, 액세사리) & 구현 HomeView에서 착용한 아이템 Fetch
  MC3Team18/MC3Team18/Global/Components/Shop/ShopItemScrollView.swift
  MC3Team18/MC3Team18/Model/ShopItemViewModel.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/ShopCharacterBody.imageset/CharacterNoFace.pdf
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/ShopCharacterBody.imageset/Contents.json
  MC3Team18/MC3Team18/View/Bubble/BubbleStatusView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/ShopView.swift
Labels: Feat

#350 Feat/#349 구현 반짝반짝 아이템 적용(별, 액세사리) & 수정 버블버블 캐릭터 레이어 (표정>버블껌>아이템 순)
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakSKScene.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleStatusView.swift
Labels: Feat

#352 Feat/#351: 구현 차곡차곡 아이템 적용(액세사리)
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: Feat

#354 UI/#353: 변경 HomeView > ShopView 진입 아이콘
  MC3Team18/MC3Team18/Global/Components/Home/TrophyView.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/ShopIcon.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShopView/ShopIcon.imageset/ShopIcon.pdf
Labels: UI
