Repository DeveloperAcademy-POSTECH/MC3_Team18_Ewook-IDLE, pull requests merged in 2023-07, with the labels that each got.

#6 Docs/#5: 수정 README
  README.md
Labels: Docs

#12 Feat/#11: 추가 HomeView 더미 버튼 2개까지
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: Feat

#15 UI/#8: 생성 Chagok 게임 관련 뷰, 간단한 배치만 (스타일 적용 안함)
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Model/2.swift
  MC3Team18/MC3Team18/Model/ChagokGameOverView.swift
  MC3Team18/MC3Team18/Model/ChagokTutorialView.swift
  MC3Team18/MC3Team18/Model/ChagokView.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokBackground.imageset/ChagokBackground.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokBackground.imageset/ChagokBackground@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokBackground.imageset/ChagokBackground@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokBackground.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/GameOverBtn.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/GameOverBtn.imageset/GameOverBtn.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/GameOverBtn.imageset/GameOverBtn@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/GameOverBtn.imageset/GameOverBtn@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/PauseBtn.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/PauseBtn.imageset/PauseBtn.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/PauseBtn.imageset/PauseBtn@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/PauseBtn.imageset/PauseBtn@3x.png
Labels: UI

#19 Renamed/#17: 이동 Chagok 관련 뷰들 폴더 위치 이동
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Model/Sample.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokView.swift
Labels: Renamed

#18 UI/#16: 생성 HomeView (UI작성 및 버튼 작동 구현)
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: UI

#23 UI/#22: 수정 Chagok 관련 뷰 폰트 설정자 적용 / 생성 빠진 폰트 설정자
  MC3Team18/MC3Team18/Global/Extension/ViewExtension.swift
  MC3Team18/MC3Team18/Global/Modifier/PretendardText.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokView.swift
Labels: UI

#28 UI/#27: 수정 텍스트 색상
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokView.swift
Labels: UI

#30 Feat/#29 추가 SpriteKit 및 ARKit 사용에 필요한 코드
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/MC3Team18App.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokARViewContainer.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokView.swift
Labels: Feat

#31 UI/#7: 생성 BubbleGumView
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundBubbleGum.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundBubbleGum.imageset/background@3x-8 1.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundBubbleGum.imageset/background@3x-8 1@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundBubbleGum.imageset/background@3x-8 1@3x.png
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumEndView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumMainView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumPauseView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumTutorialView.swift
Labels: UI

#33 Feat/#32: 수정 화면 이동 구현
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Enum/GameSelection.swift
  MC3Team18/MC3Team18/MC3Team18App.swift
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/SplashView.swift
Labels: Feat

#34 Feat/#24: 구현 BubbleGum 이미지 사이즈 증가
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumBlue.imageset/BubbleGumBlue.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumBlue.imageset/BubbleGumBlue@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumBlue.imageset/BubbleGumBlue@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumBlue.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumOrange.imageset/BubbleGumOrange.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumOrange.imageset/BubbleGumOrange@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumOrange.imageset/BubbleGumOrange@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumOrange.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumPink.imageset/BubbleGumPink@1x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumPink.imageset/BubbleGumPink@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumPink.imageset/BubbleGumPink@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/BubbleGumPink.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BubbleGumImage/Contents.json
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumMainView.swift
Labels: Feat

#39 Feat/#36: 구현 Chagok 게임 내의 화면 이동 처리
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Enum/ChagokStatus.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokMainView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: Feat

#41 UI/#40: 구현 Multi Preview 코드
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/4.swift
  MC3Team18/MC3Team18/Global/Components/MultiPreview.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokMainView.swift
Labels: UI

#43 UI/#42: 수정 statusbar hidden 적용 (BubbleGum 제외)
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokMainView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
  MC3Team18/MC3Team18/View/ContentView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/SplashView.swift
Labels: UI

#47 Assets/#46: 수정 버튼 이미지 텍스트, 스플래시, 홈 배경
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundHomeVIew.imageset/BackgroundHomeVIew.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundHomeVIew.imageset/BackgroundHomeVIew@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundHomeVIew.imageset/BackgroundHomeVIew@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundHomeVIew.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundHomeVIew.imageset/HomeViewBackground.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundSplashView.imageset/BackgroundSplashView.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundSplashView.imageset/BackgroundSplashView@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundSplashView.imageset/BackgroundSplashView@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundSplashView.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/BalloonButtonImage.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBalloon.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBalloon@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBalloon@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/ButtonCupStack.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/ButtonCupStack@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/ButtonCupStack@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/CupStackButtonImage.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/bgbg.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/bgbg.imageset/bgbg.png
Labels: Asset

#51 UI/#50: 추가 Chagok게임 캐릭터 얼굴 이미지(눈 코 입 없음)
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterActive.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterInActive.imageset/ChagokCharacterInActive.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterInActive.imageset/ChagokCharacterInActive@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterInActive.imageset/ChagokCharacterInActive@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterInActive.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/Contents.json
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: UI

#54 Feat/#48: 구현 지속시간 카운팅 기능
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumMainView.swift
Labels: Feat

#56 Asset/#55: 수정 캐릭터 얼굴 이미지, 추가 캐릭터 눈 코 입 이미지
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokEyes.imageset/ChagokEyes.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokEyes.imageset/ChagokEyes@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokEyes.imageset/ChagokEyes@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokEyes.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokMouth.imageset/ChagokMouth.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokMouth.imageset/ChagokMouth@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokMouth.imageset/ChagokMouth@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokMouth.imageset/Contents.json
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: Asset

#58 Feat/#57: 구현 차곡차곡 왼쪽 뷰 컵 5개가 쌓이도록 구현, 각각 다른 컵이 쌓임
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Feat

#59 Feat/#37: 구현 캐릭터 표정변화 애니메이션
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionDefault.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionDefault.imageset/자산 24@3x-8 1.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionDefault.imageset/자산 24@3x-8 1@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionDefault.imageset/자산 24@3x-8 1@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionGameOver.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionGameOver.imageset/자산 22@3x-8.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionGameOver.imageset/자산 22@3x-8@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionGameOver.imageset/자산 22@3x-8@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionSleepy.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionSleepy.imageset/자산 23@3x-8.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionSleepy.imageset/자산 23@3x-8@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionSleepy.imageset/자산 23@3x-8@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionTired.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionTired.imageset/자산 21@3x-8.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionTired.imageset/자산 21@3x-8@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionTired.imageset/자산 21@3x-8@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/자산 19@3x-8 4.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/자산 19@3x-8 4@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/자산 19@3x-8 4@3x.png
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumMainView.swift
Labels: Feat

#62 Feat/#61: 수정 튜토리얼, 게임 일시정지, 게임오버 로직 수정
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokMainView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: Feat

#64 Asset/#63: 수정 Bubblegum Game 캐릭터의 이미지가 제대로 적용되지 않던 문제를 수정
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/자산 19@3x-8 5.png
Labels: Asset

#66 Feat/#60: 구현 BubbleGum 화면 이동
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Enum/BubbleGumStatus.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumMainView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumPauseView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumTutorialView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: Feat

#70 Feat/#68: 구현 ChagokSKScene <-> ChagokGameView간 데이터 공유
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Feat

#71 Feat/#69: 구현 BubbleGumView 홈 화면 이동 버튼
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
Labels: Feat

#73 Feat/#72:구현 왼쪽 컵스택과 오른쪽 컵 스택이 같은지 확인하는 로직 구현
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Feat

#75 Feat/#74: 구현 입모양에따라 캐릭터 입모양 변경
  MC3Team18/MC3Team18/View/Chagok/ChagokARViewContainer.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: Feat

#77 Feat/#76: 구현 일시정지, 게임 오버 화면 버튼 Glass Moriphism 구현, 디자인 적용
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/CustomBlurView.swift
  MC3Team18/MC3Team18/Global/Extension/NSObjectExtension.swift
  MC3Team18/MC3Team18/Global/Extension/UIViewExtension.swift
  MC3Team18/MC3Team18/Global/Extension/UIVisualEffectViewExtension.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOverBorder.imageset/ButtonGameOverBorder.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOverBorder.imageset/ButtonGameOverBorder@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOverBorder.imageset/ButtonGameOverBorder@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonGameOverBorder.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPauseBorder.imageset/ButtonPauseBorder.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPauseBorder.imageset/ButtonPauseBorder@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPauseBorder.imageset/ButtonPauseBorder@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonPauseBorder.imageset/Contents.json
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
Labels: Feat

#78 Bug/#67: 수정 버블껌 게임 종료 시 애니메이션 초기화
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
Labels: Bug

#80 Asset/#79: 추가 MainCharacterBody 그림자 없는 이미지로 교체
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionSleepy.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionSleepy.imageset/ExpressionSleep.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionSleepy.imageset/ExpressionSleep@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterExpressionImage/ExpressionSleepy.imageset/ExpressionSleep@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/MainCharacterBody.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/MainCharacterBody@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/MainCharacterBody@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/자산 19@3x-8 1.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/자산 19@3x-8 1@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/자산 19@3x-8 1@3x.png
Labels: Asset

#82 UI/#81: GameOverView의 버튼 GlassMorphism적용
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
Labels: UI

#84 Feat/#83: 립트릴&텅트릴 사운드 분류
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Model/MySoundClassifier0715.mlmodel
  MC3Team18/MC3Team18/View/BubbleGum/AudioStreamManager.swift
  MC3Team18/MC3Team18/View/BubbleGum/AudioStreamObserver.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumTutorialView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
Labels: Feat

#86 Feat/#85: 구현 chagokScore 점수 기능
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Feat

#88 Feat/#87: 구현 게임 상태 일시정지 & 타이머
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
Labels: Feat

#90 Bug/#89 수정 다음 라운드 입모양 컵이 사라지는 현상 수정
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Bug

#94 Bug/#93: 수정 Tutorial 화면에서 게임 멈춰있는 상태가 아닌 현상 수정, gameStatus 관련 잔버그개선
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
Labels: Bug

#96 [Asset] 수정 BubblegumGame 캐릭터 body 이미지 제대로 로드 안되는 버그 수정
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/MainCharacterBody.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/MainCharacterBody@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/MainCharacterBody.imageset/MainCharacterBody@3x.png
Labels: Asset

#103 Bug/#100 수정 ChagokGameSKScene update 방지하는 변수 통합
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
Labels: Bug

#99 Feat/#98: 구현 버블껌 게임 시작, 종료 시 햅틱 모션
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Extension/Haptics.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
Labels: Feat

#106 Feat/#97 구현 풍선껌 흔들리는 애니메이션, 난이도 조정에 따른 애니메이션 max값 재설정
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
Labels: Feat

#108 Feat/#107: 수정 점수 소수점 첫째자리까지 출력
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
Labels: Feat

#110 UI/#109 수정 패딩, 그림자, X버튼, BestScore 텍스트
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumTutorialView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
Labels: UI

#116 Feat/#115: 수정 버블껌 게임 종료 트리거
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
Labels: Feat

#117 Feat/#105: 구현 풍선껌 게임 최고기록 저장
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
Labels: Feat

#119 Feat/#102: 구현 다시 보지 않기 버튼
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumTutorialView.swift
Labels: Feat

#122 Bug/#111: 수정 버블껌 게임 햅틱
  MC3Team18/MC3Team18/View/BubbleGum/AudioStreamManager.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
Labels: Bug

#124 Feat/#123: 구현 버블껌 BGM 재생
  MC3Team18/MC3Team18/View/BubbleGum/AudioStreamManager.swift
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: Feat

#129 Feat/#128: 구현 최고기록 갱신 텍스트 추가
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
Labels: Feat

#131 UI/#127 수정 피그마 변경사항 UI 적용 + Lottie Package 추가
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MC3Team18/MC3Team18/Global/Components/LottieView.swift
  MC3Team18/MC3Team18/Resources/Lottie/lottieAnima_chagok.json
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumTutorialView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
Labels: UI

#134 UI/#132 수정 Chagok - GameOver, Pause retry 애니메이션 수정, 추가 Tutorial 로티 추가
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Resources/Lottie/lottieAnima_chagok.json
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
Labels: UI

#133 Feat/#118: 구현 BubbleGum게임 지속시간 점수화
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
Labels: Feat

#136 UI/#135 수정 Chagok 게임 실행시 얼굴 인식 안될 때 점선으로 나오도록 수정
  MC3Team18/MC3Team18/View/Chagok/ChagokARViewContainer.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: UI

#138 UI/#130: 구현 BubbleGum 게임 화면 트랜지션
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: UI

#139 UI/#137 추가 최고기록 경신 시 로티 애니메이션 bubble & chagok
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Resources/Lottie/CelebLottieAnima.json
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
Labels: UI

#141 Feat/#140: 구현 컵 5개 터질 시 스코어 애니메이션 구현
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Feat

#145 Bug/#144: 수정 차곡 게임오버에서 리트라이할 시 게임정보 제대로 초기화되도록 수정
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
Labels: Bug

#147 UI/#146 수정 스플래시 화면 로고 수정
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/SplashLogo.imageset/SplashLogoImage.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/SplashLogo.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/SplashLogo.imageset/SplashLogo.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/SplashLogo.imageset/SplashLogo@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/SplashLogo.imageset/SplashLogo@3x.png
  MC3Team18/MC3Team18/View/SplashView.swift
Labels: UI

#149 Asset/#146 교체 입모양 '우' 이미지 교체
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/4dd.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/4r4r.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/Cup_pink@3x-8.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup@3x.png
Labels: Asset

#153 Asset/#150 교체 PinkCup 그림자 없는 이미지 / LeftCupStack
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup@3x.png
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: Asset

#155 Feat/#154: 구현 앱 실행 도중 화면 꺼짐 상태 설정
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: Feat

#159 Asset/#158: 교체 ChagokMouth 파일 이빨 있는 것으로 교체 (피그마 디자인 완벽 대응 아님)
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokMouth.imageset/ChagokMouth.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokMouth.imageset/ChagokMouth@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Chagok/ChagokMouth.imageset/ChagokMouth@3x.png
Labels: Asset

#161 Feat/#160: 수정 얼굴 인식 안 될 시 점선으로 이미지 변경하는 코드 수정
  MC3Team18/MC3Team18/View/Chagok/ChagokARViewContainer.swift
Labels: Feat

#165 UI/#162: 구현 기록뷰 UI 그리기 (화면 이동 미처리)
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Menu/MenuBottomScoresView.swift
  MC3Team18/MC3Team18/Global/Components/Menu/MenuHexgagonView.swift
  MC3Team18/MC3Team18/Global/Components/Menu/MenuMyRecordsView.swift
  MC3Team18/MC3Team18/Global/Extension/ColorExtension.swift
  MC3Team18/MC3Team18/Global/Extension/ViewExtension.swift
  MC3Team18/MC3Team18/Global/Modifier/PretendardText.swift
  MC3Team18/MC3Team18/MC3Team18App.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/CobaltBlue.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/Gray50.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/MenuGradient.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/MenuGradient.imageset/MenuGradient.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/MenuGradient.imageset/MenuGradient@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/MenuGradient.imageset/MenuGradient@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterActive.imageset/ChagokCharacterActive@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterActive.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterInActive.imageset/ChagokCharacterInActive.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterInActive.imageset/ChagokCharacterInActive@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterInActive.imageset/ChagokCharacterInActive@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokCharacterInActive.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokEyes.imageset/ChagokEyes.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokEyes.imageset/ChagokEyes@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokEyes.imageset/ChagokEyes@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokEyes.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouth.imageset/ChagokMouth.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouth.imageset/ChagokMouth@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouth.imageset/ChagokMouth@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/ChagokMouth.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Chagok/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/MenuHexagon.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/MenuHexagon.imageset/MenuHexagon.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/MenuHexagon.imageset/MenuHexagon@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/MenuHexagon.imageset/MenuHexagon@3x.png
  MC3Team18/MC3Team18/Resources/Fonts/Pretendard-Medium.otf
  MC3Team18/MC3Team18/View/MenuView.swift
Labels: UI

#168 UI/#167 구현 BestScore 이미지 추가 및 UI 구현
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Menu/MenuBottomScoresView.swift
  MC3Team18/MC3Team18/Global/Components/Menu/MenuMyRecordsView.swift
  MC3Team18/MC3Team18/Global/Extension/ViewExtension.swift
  MC3Team18/MC3Team18/Global/Modifier/PretendardText.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/BubbleGumBest.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/BubbleGumBest@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/BubbleGumBest@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/ChagokBest.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/ChagokBest@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/Frame 71@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/StarBest.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/StarBest.imageset/StarBest.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/StarBest.imageset/StarBest@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/StarBest.imageset/StarBest@3x.png
  MC3Team18/MC3Team18/Resources/Fonts/Pretendard-ExtraLight.otf
  MC3Team18/MC3Team18/View/MenuView.swift
Labels: UI

#170 UI/#169 추가 홈화면 별 게임 버튼, 트로피 버튼 추가 / 구현 MenuView 화면이동 구현
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Home/TrophyView.swift
  MC3Team18/MC3Team18/Global/Enum/GameSelection.swift
  MC3Team18/MC3Team18/Global/Extension/ColorExtension.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/Orange.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBalloon.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBalloon@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBalloon@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/ButtonCupStack.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/ButtonCupStack@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/ButtonCupStack@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonStar.imageset/ButtonStar.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonStar.imageset/ButtonStar@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonStar.imageset/ButtonStar@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonStar.imageset/Contents.json
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/MenuView.swift
Labels: UI

#172 Feat/#171: 구현 StatisticView(데일리미션 + BestScore) 데이터 연결
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Menu/MenuBottomScoresView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/MenuView.swift
Labels: Feat

#175 Bug/#174 수정 BestScore가 nil일 시 기록뷰 넘어갈 때 앱 크래시 나는 현상 수정
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Menu/MenuBottomScoresView.swift
Labels: Bug

#178 Bug/#176 : 수정 풍선껌 BestScore쪽 초 소수점 단위로
  MC3Team18/MC3Team18/Global/Components/Menu/MenuBottomScoresView.swift
Labels: Bug

#179 Feat/#177: 구현 Daily Drill 공유 기능 (기록된 일수등은 임시 데이터)
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Menu/DailyShareView.swift
  MC3Team18/MC3Team18/Global/Utils/TransferableUIImage.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/BackgroundDailyShare.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/BackgroundDailyShare@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/BackgroundDailyShare@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/Contents.json
  MC3Team18/MC3Team18/View/MenuView.swift
Labels: Feat

#182 UI/#180: 구현 BestScore UI 그리기 (공유 기능 x)
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Games/BestScoreShareView.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundBestScoreShare.imageset/BackgroundBestScoreShare.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundBestScoreShare.imageset/BackgroundBestScoreShare@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundBestScoreShare.imageset/BackgroundBestScoreShare@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundBestScoreShare.imageset/Contents.json
Labels: UI

#183 UI/#181: 생성 별따먹기 StarGameView, StarTutorialView, StarPauseView, StarGameOverView
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundStar.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundStar.imageset/StarBackground.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundStar.imageset/StarBackground@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundStar.imageset/StarBackground@3x.png
  MC3Team18/MC3Team18/View/Star/StarGameOverView.swift
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
  MC3Team18/MC3Team18/View/Star/StarPauseView.swift
  MC3Team18/MC3Team18/View/Star/StarTutorialView.swift
Labels: UI

#185 Feat/#184: 구현 StarGame 화면 간 연결, 화면 트랜지션
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Enum/StarStatus.swift
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/Star/StarGameOverView.swift
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
  MC3Team18/MC3Team18/View/Star/StarPauseView.swift
  MC3Team18/MC3Team18/View/Star/StarTutorialView.swift
Labels: Feat

#187 Asset/#186 추가 앱아이콘
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/102.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/92.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Asset

#188 Feat/#166: 수정 버블껌 게임 ML 모델, 추가 은하수 게임 ML 모델
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Model/MySoundClassifier0715.mlmodel
  MC3Team18/MC3Team18/Model/Trill_35_05_50.mlmodel
  MC3Team18/MC3Team18/Model/Voice_35_05_75.mlmodel
  MC3Team18/MC3Team18/Model/Voice_35_065_75.mlmodel
  MC3Team18/MC3Team18/View/BubbleGum/AudioStreamManager.swift
  MC3Team18/MC3Team18/View/BubbleGum/AudioStreamObserver.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
Labels: Feat

#190 Bug/#189 게임 도중 얼굴 인식 벗어날 때 점선으로 표시
  MC3Team18/MC3Team18/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  MC3Team18/MC3Team18/View/Chagok/ChagokARViewContainer.swift
Labels: Bug

#193 Bug/#192 : 튜토리얼 문구 변경
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumTutorialView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
  MC3Team18/MC3Team18/View/Star/StarTutorialView.swift
Labels: Bug

#196 Setting/#195: 수정 폰트 ViewModifier 이름
  MC3Team18/MC3Team18/Global/Modifier/PretendardText.swift
Labels: Setting

#198 Feat/#197: 구현 반짝반짝 게임 소리 인식 없이 기능 구현
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Star/StarGameOverView.swift
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
  MC3Team18/MC3Team18/View/Star/StarPauseView.swift
  MC3Team18/MC3Team18/View/Star/StarSKScene.swift
  MC3Team18/MC3Team18/View/Star/StarTutorialView.swift
Labels: Feat

#202 Feat/#200: 추가 StarAudioStreamManager, StarAudioStreamObserver
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Star/StarAudioStreamManager.swift
  MC3Team18/MC3Team18/View/Star/StarAudioStreamObserver.swift
Labels: Feat

#210 Feat/#203 구현 반짝반짝 게임 ML 모델 연결
  MC3Team18/MC3Team18/View/Star/StarAudioStreamManager.swift
  MC3Team18/MC3Team18/View/Star/StarGameOverView.swift
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
  MC3Team18/MC3Team18/View/Star/StarPauseView.swift
  MC3Team18/MC3Team18/View/Star/StarSKScene.swift
Labels: Feat

#211 UI/#199
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18.xcodeproj/xcshareddata/xcschemes/MC3Team18.xcscheme
  MC3Team18/MC3Team18/Global/Components/Menu/MenuBottomScoresView.swift
  MC3Team18/MC3Team18/Global/Components/Menu/MenuHexgagonView.swift
  MC3Team18/MC3Team18/Global/Components/Menu/MenuMyRecordsView.swift
  MC3Team18/MC3Team18/Global/Extension/ColorExtension.swift
  MC3Team18/MC3Team18/Global/Extension/ViewExtension.swift
  MC3Team18/MC3Team18/Global/Modifier/PretendardText.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/Shadow.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Color/ShadowBlue.colorset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/BubbleGumBest.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/BubbleGumBest@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/BubbleGumBest@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/Frame 73.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/Frame 73@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/BubbleGumBest.imageset/Frame 73@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/ChagokBest.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/ChagokBest@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/Frame 71.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/Frame 71@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Menu/ChagokBest.imageset/Frame 71@3x.png
  MC3Team18/MC3Team18/View/MenuView.swift
Labels: UI

#213 UI/#208: 수정 GameOverView 최고기록 갱신일 경우 UI
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Star/StarGameOverView.swift
Labels: UI

#216 UI/#212 수정 오늘의 드릴 완료 공유 뷰 상태 따라 텍스트 변경
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Menu/DailyShareView.swift
  MC3Team18/MC3Team18/Global/Components/Menu/MenuHexgagonView.swift
Labels: UI

#218 Asset/215 추가 반짝반짝 BGM
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Enum/SoundNames.swift
  MC3Team18/MC3Team18/Resources/Sound/banzzakBGM.mp3
  MC3Team18/MC3Team18/View/Star/StarAudioStreamManager.swift
Labels: Asset

#220 Feat/#214: 구현 반짝반짝 최고기록 저장, 통계뷰 연결
  MC3Team18/MC3Team18/Global/Components/Menu/MenuBottomScoresView.swift
  MC3Team18/MC3Team18/View/Star/StarGameOverView.swift
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
  MC3Team18/MC3Team18/View/Star/StarSKScene.swift
Labels: Feat

#223 UI/#219: 수정 홈 화면 padding, MenuView padding 수정, Splash 글씨 자간 수정, tutorial 문구 top padding / 추가 버블버블튜토리얼 Lottie추가
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Resources/Lottie/lottieAnima_bubble.json
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumTutorialView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/MenuView.swift
  MC3Team18/MC3Team18/View/SplashView.swift
  MC3Team18/MC3Team18/View/Star/StarTutorialView.swift
Labels: UI

#225 Feat/#221: 구현 반짝반짝 데일리미션 수행 여부 확인 로직
  MC3Team18/MC3Team18/View/Star/StarGameOverView.swift
Labels: Feat

#227 UI/#224 수정 반짝반짝 튜토리얼 로티 애니메이션 추가
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Resources/Lottie/lottieAnima_shiningStar.json
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
  MC3Team18/MC3Team18/View/Star/StarTutorialView.swift
Labels: UI

#229 Bug/#228: 수정 버블버블, 반짝반짝 게임 AudioEngine 종료
  MC3Team18/MC3Team18/View/BubbleGum/AudioStreamManager.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameOverView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumGameView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumStatusView.swift
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumWaitingView.swift
  MC3Team18/MC3Team18/View/Star/StarAudioStreamManager.swift
  MC3Team18/MC3Team18/View/Star/StarGameOverView.swift
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
  MC3Team18/MC3Team18/View/Star/StarPauseView.swift
Labels: Bug

#232 Asset/#230 교체 홈화면 게임 버튼 이미지
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBalloon.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBalloon@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBalloon@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBubble.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBubble@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/ButtonBubble@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBalloon.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/ButtonCupStack.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/ButtonCupStack@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonCupStack.imageset/ButtonCupStack@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonStar.imageset/ButtonStar.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonStar.imageset/ButtonStar@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonStar.imageset/ButtonStar@3x.png
  MC3Team18/MC3Team18/View/SplashView.swift
Labels: Asset

#233 Asset/#231 교체 반짝반짝 캐릭터 이미지
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakDefault.imageset/BanzzakDefault 1.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakDefault.imageset/BanzzakDefault.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakDefault.imageset/BanzzakDefault@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakDefault.imageset/BanzzakDefault@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakDefault.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakTrill.imageset/BanzzakTrill 1.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakTrill.imageset/BanzzakTrill.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakTrill.imageset/BanzzakTrill@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakTrill.imageset/BanzzakTrill@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakTrill.imageset/Contents.json
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
Labels: Asset

#235 Setting/#234 설정 세로모드 고정, 앱 권한 설정 텍스트 수정
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
Labels: Setting

#240 Asset/#239 수정 반짝반짝 캐릭터 이미지 해상도
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakDefault.imageset/BanzzakDefault.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakDefault.imageset/BanzzakDefault@3x 1.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakDefault.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakTrill.imageset/BanzzakTrill.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Banzzak/BanzzakTrill.imageset/Contents.json
Labels: Asset

#242 Feat/#237 수정 차곡 튜토리얼 시 배경 캐릭터 점선으로 표시, 버블버블 차곡 튜토리얼 opacity ,차곡 처음 얼굴 인식 전 점선에서 타이머 시작 안되게 수정
  MC3Team18/MC3Team18/View/BubbleGum/BubbleGumTutorialView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokARViewContainer.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
Labels: Feat

#244 UI/#238 수정 반짝반짝 캐릭터, 별 나오는 위치 조정
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
  MC3Team18/MC3Team18/View/Star/StarSKScene.swift
Labels: UI

#247 Feat/#246
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
Labels: Feat

#249 UI/#248 수정 스플래시 로고 & 텍스트가 조금 위로 올라가도록 수정
  MC3Team18/MC3Team18/Resources/Assets.xcassets/FullScreenSplash.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/FullScreenSplash.imageset/FullScreenSplash.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/FullScreenSplash.imageset/FullScreenSplash@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/FullScreenSplash.imageset/FullScreenSplash@3x.png
  MC3Team18/MC3Team18/View/SplashView.swift
Labels: UI

#252 Feat/#250 수정 반짝 게임 소리를 내면 시작하도록 / 수정 튜토리얼 시 일시정지 버튼이 보이지 않도록
  MC3Team18/MC3Team18/View/Star/StarGameOverView.swift
  MC3Team18/MC3Team18/View/Star/StarGameView.swift
  MC3Team18/MC3Team18/View/Star/StarPauseView.swift
  MC3Team18/MC3Team18/View/Star/StarSKScene.swift
  MC3Team18/MC3Team18/View/Star/StarTutorialView.swift
Labels: Feat

#257 Feat/#255 수정 별 딜레이 1 -> 0.5초 & 아rrrr 시 바로 별이 나오도록 수정
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakSKScene.swift
Labels: Feat

#258 [Feat] 수정 차곡차곡 노란색 컵 판정 볼 부풀리기로, 빨간색 컵 인식 개선
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/View/Chagok/ChagokARViewContainer.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Feat

#260 Renamed/#259 수정 UserDefaults -> @AppStorage 방식으로 변경
  MC3Team18/MC3Team18/Global/Components/Games/BestScoreShareView.swift
  MC3Team18/MC3Team18/Global/Components/Record/RecordBestScoresView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameOverView.swift
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleStatusView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleTutorialView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokTutorialView.swift
Labels: Renamed

#262 Feat/#261: 구현 반짝반짝 튜토리얼 다시 안보기
  MC3Team18/MC3Team18/View/Banjjak/BanjjakTutorialView.swift
Labels: Feat

#263 Feat/#251: 수정 디졸브방식 화면전환
  MC3Team18/MC3Team18/Global/Components/Home/TrophyView.swift
  MC3Team18/MC3Team18/Global/Enum/GameSelection.swift
  MC3Team18/MC3Team18/Global/Extension/ViewExtension.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameOverView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleWaitingView.swift
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/RecordView.swift
Labels: Feat

#266 Feat/#265: 수정 반짝반짝 별이 붙는 범위 수정 & 최대 높이 수정
  MC3Team18/MC3Team18/View/Banjjak/BanjjakSKScene.swift
Labels: Feat

#268 Feat/#267 반짝 버튼 이미지 변경
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBanjjak.imageset/ButtonBanjjak.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBanjjak.imageset/ButtonBanjjak@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBanjjak.imageset/ButtonBanjjak@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBanjjak.imageset/ButtonStar.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBanjjak.imageset/ButtonStar@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBanjjak.imageset/ButtonStar@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ButtonImage/ButtonBanjjak.imageset/Contents.json
Labels: Feat

#270 Feat/#269: 수정 chagok 점수 기준 줄 -> 개
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Record/RecordBestScoresView.swift
  MC3Team18/MC3Team18/Global/Components/Record/RecordHexgagonView.swift
  MC3Team18/MC3Team18/View/RecordView.swift
Labels: Feat

#272 UI/#271: 수정 Chalk 레이아웃
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokPauseView.swift
Labels: UI

#275 Feat/#273 노란컵, 보라컵 동시에 판정 발생하지 않게 수정
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Feat

#277 Bug/#276: 수정 버블버블 튜토리얼 저장, 캐릭터 안나오는 버그
  MC3Team18/MC3Team18/View/Bubble/BubbleGameOverView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleStatusView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleTutorialView.swift
  MC3Team18/MC3Team18/View/RecordView.swift
Labels: Bug

#279 UI/#278 홈화면 코인 및 넛지 아이콘 배치, ShopView 연결 (임시 뷰)
  MC3Team18/MC3Team18.xcodeproj/project.pbxproj
  MC3Team18/MC3Team18/Global/Components/Home/TrophyView.swift
  MC3Team18/MC3Team18/Global/Extension/ViewExtension.swift
  MC3Team18/MC3Team18/Global/Modifier/PostNoBillsJaffnaText.swift
  MC3Team18/MC3Team18/MC3Team18App.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconNudge.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconNudge.imageset/IconNudge.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconNudge.imageset/IconNudge@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconNudge.imageset/IconNudge@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconNudgeBackground.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconNudgeBackground.imageset/IconNudgeBackground.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconNudgeBackground.imageset/IconNudgeBackground@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconNudgeBackground.imageset/IconNudgeBackground@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconShop.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconShop.imageset/IconShop.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconShop.imageset/IconShop@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Home/IconShop.imageset/IconShop@3x.png
  MC3Team18/MC3Team18/Resources/Fonts/PostNoBillsJaffna-ExtraBold.ttf
  MC3Team18/MC3Team18/View/HomeView.swift
  MC3Team18/MC3Team18/View/ShopView.swift
Labels: UI

#282 Asset/#280 교체 공유 배경 이미지
  MC3Team18/MC3Team18/Global/Components/Games/BestScoreShareView.swift
  MC3Team18/MC3Team18/Global/Components/Record/RecordDailyShareView.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/BackgroundDailyShare.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/BackgroundDailyShare@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/BackgroundDailyShare@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/Rectangle 58.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/Rectangle 58@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/BackgroundImage/BackgroundDailyShare.imageset/Rectangle 58@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_banjjak.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_banjjak.imageset/Share_BestScore_banjjak.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_banjjak.imageset/Share_BestScore_banjjak@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_banjjak.imageset/Share_BestScore_banjjak@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_bubble.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_bubble.imageset/ShareImage_BestScore_bubble.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_bubble.imageset/ShareImage_BestScore_bubble@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_bubble.imageset/ShareImage_BestScore_bubble@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_chagok.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_chagok.imageset/ShareImage_BestScore_chagok.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_chagok.imageset/ShareImage_BestScore_chagok@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/ShareBestScore_chagok.imageset/ShareImage_BestScore_chagok@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/Share_BestScore_Bubble.imageset/ShareImage_BestScore_Bubble.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/Share_BestScore_Bubble.imageset/ShareImage_BestScore_Bubble@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/Share_BestScore_Bubble.imageset/ShareImage_BestScore_Bubble@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/Share_BestScore_Chagok.imageset/ShareImage_BestScore_Chagok.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/Share_BestScore_Chagok.imageset/ShareImage_BestScore_Chagok@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/Share_BestScore_Chagok.imageset/ShareImage_BestScore_Chagok@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/Share_BestScore_banjjak.imageset/ShareImage_BestScore_Star.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/Share_BestScore_banjjak.imageset/ShareImage_BestScore_Star@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/ShareBestScoreImage/Share_BestScore_banjjak.imageset/ShareImage_BestScore_Star@3x.png
  MC3Team18/MC3Team18/View/HomeView.swift
Labels: Asset

#285 UI/#283: 수정 YellowCup, PickCup 이미지 교체
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/23e.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/23rf2r.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/Cup_yellow@3x-8.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/YellowCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/YellowCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/YellowCup@3x.png
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: UI

#287 Bug/#286: 수정 cupNode를 함수로 구현된 것으로 코드 교체
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Bug

#288 UI/#281 수정 RecordView, BestScoreShareView, TrophyView
  MC3Team18/MC3Team18/Global/Components/Games/BestScoreShareView.swift
  MC3Team18/MC3Team18/Global/Components/Home/TrophyView.swift
  MC3Team18/MC3Team18/Global/Components/Record/RecordDailyShareView.swift
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/CharacterMissionDone.imageset/CharacterMissionDone.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/CharacterMissionDone.imageset/CharacterMissionDone@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/CharacterMissionDone.imageset/CharacterMissionDone@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/CharacterMissionDone.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/CharacterMissionStart.imageset/CharacterStart.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/CharacterMissionStart.imageset/CharacterStart@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/CharacterMissionStart.imageset/CharacterStart@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/CharacterMissionStart.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/RecordShareLogo.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/RecordShareLogo.imageset/logo_filled.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/RecordShareLogo.imageset/logo_filled@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/Record/RecordShareLogo.imageset/logo_filled@3x.png
  MC3Team18/MC3Team18/View/RecordView.swift
Labels: UI

#289 Feat/#284 추가 유저 코인 보유량 totalCoin 변수
  MC3Team18/MC3Team18/Global/Components/Home/TrophyView.swift
Labels: Feat

#291 Feat/#290 추가 차곡차곡 1줄 완성 시 시간 3초 더 줌
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: Feat

#293 Feat/#292 추가 게임종료 후 점수 비례 코인보상
  MC3Team18/MC3Team18/View/Banjjak/BanjjakGameOverView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameOverView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameOverView.swift
  MC3Team18/MC3Team18/View/ShopView.swift
Labels: Feat

#303 Asset/#302: 수정 컵 이미지 교체 & 사이즈 수정
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/BlueCup.imageset/2xx.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/BlueCup.imageset/3xxx.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/BlueCup.imageset/BlueCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/BlueCup.imageset/BlueCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/BlueCup.imageset/BlueCup@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/BlueCup.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/BlueCup.imageset/Cup_blue@3x-8.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/GreenCup.imageset/2s.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/GreenCup.imageset/3d.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/GreenCup.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/GreenCup.imageset/Cup_green@3x-8.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/GreenCup.imageset/GreenCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/GreenCup.imageset/GreenCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/GreenCup.imageset/GreenCup@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/PinkCup.imageset/PinkCup@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/RedCup.imageset/4f34f4.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/RedCup.imageset/4f4.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/RedCup.imageset/Contents.json
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/RedCup.imageset/Cup_red@3x-8.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/RedCup.imageset/RedCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/RedCup.imageset/RedCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/RedCup.imageset/RedCup@3x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/YellowCup.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/YellowCup@2x.png
  MC3Team18/MC3Team18/Resources/Assets.xcassets/Image/CharacterImage/YellowCup.imageset/YellowCup@3x.png
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokSKScene.swift
Labels: Asset

#305 UI/#304 수정 BestScoreShareView 배경 이미지 불러오는 String, 수정 버블버블 배경 Offset 값 -740 > -700, 수정 차곡차곡 TapToStart UI, 타이머 레이아웃
  MC3Team18/MC3Team18/Global/Components/Games/BestScoreShareView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleGameView.swift
  MC3Team18/MC3Team18/View/Bubble/BubbleStatusView.swift
  MC3Team18/MC3Team18/View/Chagok/ChagokGameView.swift
Labels: UI
